[
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "['Some reason']",
    "stack": [
      "src/oscar/apps/basket/forms.py:130",
      "src/oscar/apps/basket/forms.py:118"
    ]
  },
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "['Some reason']",
    "stack": [
      "src/oscar/apps/basket/forms.py:137",
      "src/oscar/apps/basket/forms.py:130",
      "src/oscar/apps/basket/forms.py:118"
    ]
  }
]