[
  {
    "class": "django.db.utils.IntegrityError",
    "message": "duplicate key value violates unique constraint \"catalogue_product_upc_key\"\nDETAIL:  Key (upc)=(bah) already exists.\n",
    "stack": [
      "src/oscar/apps/catalogue/abstract_models.py:590"
    ]
  }
]